/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "homeapp": [],
    "homeapp2": [],
    "rewind": [],
    "create": [],
    "checkresult": [
        {
            "name": "idGuess",
            "required": true
        }
    ],
    "change.locale": [],
    "login": [],
    "logout": [],
    "register": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "password.confirm": [],
    "home": [],
    "player": [],
    "newplayer": [],
    "editplayer": [
        {
            "name": "id",
            "required": true
        }
    ],
    "updateplayer": [],
    "searchplayer": [],
    "newclub": [
        {
            "name": "idPlayer",
            "required": true
        }
    ],
    "newtitle": [
        {
            "name": "idPlayer",
            "required": true
        }
    ],
    "updatetitles": [
        {
            "name": "idPlayer",
            "required": true
        }
    ]
}
}
export {};
