<?php 

return [
	'en' => [
		'h2-1' => 'Welcome to Footble',
		'h3-1' => 'The football Wordle game',
		'p-1' => "We use cookies and similar technologies to enhance your experience, analyze site performance, and deliver personalized ads. Here’s what you need to know",
		'localstorage' => 'Local storage',
		'p-2' => "Footble stores game progress (e.g., scores or settings) directly in your browser for functionality. No personal data is collected or sent to us.",
		'analytics' => 'Analytics',
		'p-3' => "We use Google Analytics to understand how our site is used. This may involve cookies to track anonymized usage patterns.",
		'advertising' => 'Advertising',
		'p-4' => "We partner with ad providers that may use cookies to serve relevant ads based on your interests and browsing behavior.",
		'p-5' => "By continuing to use Footble, you consent to our use of cookies as described. You can manage your cookie preferences through your browser settings at any time.",
		'p-6' => "For more details, see our",
		'privacypolicy' => "Privacy Policy",
		'consent' => 'Consent',
		'noconsent' => 'No Consent'
	],
	'es' => [
		'h2-1' => "Bienvenido a Footble",
		'h3-1' => "El juego Wordle de fútbol",
		'p-1' => "Utilizamos cookies y tecnologías similares para mejorar su experiencia, analizar el rendimiento del sitio y ofrecer anuncios personalizados. Esto es lo que necesitas saber",
		'localstorage' => "Almacenamiento local",
		'p-2' => "Footble almacena el progreso del juego (por ejemplo, puntuaciones o ajustes) directamente en tu navegador para mayor funcionalidad. No se recogen ni nos envían datos personales.",
		'analytics' => "Analytics",
		'p-3' => "Usamos Google Analytics para entender cómo se usa nuestro sitio. Esto puede implicar el uso de cookies para rastrear patrones de uso anónimos",
		'advertising' => "Publicidad",
		'p-4' => "Colaboramos con proveedores de publicidad que pueden utilizar cookies para publicar anuncios relevantes basados en tus intereses y comportamiento de navegación.",
		'p-5' => "Al continuar utilizando Footble, aceptas el uso que hacemos de las cookies, tal y como se ha descrito. Puedes gestionar tus preferencias de cookies a través de la configuración de tu navegador en cualquier momento.",
		'p-6' => "Para más información, consulta nuestra",
		'privacypolicy' => "Política de Privacidad",
		'consent' => "Consentir",
		'noconsent' => "No Consentir",
	],
	'fr' => [
		'h2-1' => "Bienvenue sur Footble",
		'h3-1' => "Le jeu Wordle du football",
		'p-1' => "Nous utilisons des cookies et des technologies similaires pour améliorer votre expérience, analyser les performances du site et diffuser des publicités personnalisées. Voici ce que vous devez savoir",
		'localstorage' => "Stockage local",
		'p-2' => "Footble stocke la progression du jeu (par exemple, scores ou paramètres) directement dans votre navigateur pour assurer son fonctionnement. Aucune donnée personnelle n'est collectée ou envoyée à nous.",
		'analytics' => "Analytics",
		'p-3' => "Nous utilisons Google Analytics pour comprendre comment notre site est utilisé. Cela peut impliquer des cookies pour suivre des modèles d'utilisation anonymisés.",
		'advertising' => "Publicité",
		'p-4' => "Nous collaborons avec des fournisseurs de publicités qui peuvent utiliser des cookies pour diffuser des annonces pertinentes basées sur vos centres d'intérêt et votre comportement de navigation.",
		'p-5' => "En continuant à utiliser Footble, vous consentez à notre utilisation des cookies telle que décrite. Vous pouvez gérer vos préférences de cookies via les paramètres de votre navigateur à tout moment.",
		'p-6' => "Pour plus de détails, consultez notre",
		'privacypolicy' => "Politique de confidentialité",
		'consent' => "Consentir",
		'noconsent' => "Ne pas consentir",
	],
	'de' => [
		'h2-1' => "Willkommen bei Footble",
		'h3-1' => "Das Fußball-Wordle-Spiel",
		'p-1' => "Wir verwenden Cookies und ähnliche Technologien, um deine Erfahrung zu verbessern, die Website-Leistung zu analysieren und personalisierte Werbung bereitzustellen. Das musst du wissen",
		'localstorage' => "Lokaler Speicher",
		'p-2' => "Footble speichert den Spielfortschritt (z. B. Punkte oder Einstellungen) direkt in deinem Browser für die Funktionalität. Es werden keine persönlichen Daten gesammelt oder an uns gesendet.",
		'analytics' => "Analytics",
		'p-3' => "Wir verwenden Google Analytics, um zu verstehen, wie unsere Website genutzt wird. Dies kann Cookies beinhalten, um anonymisierte Nutzungsmuster zu verfolgen.",
		'advertising' => "Werbung",
		'p-4' => "Wir arbeiten mit Werbeanbietern zusammen, die Cookies verwenden können, um relevante Anzeigen basierend auf deinen Interessen und deinem Surfverhalten zu schalten.",
		'p-5' => "Indem du Footble weiterhin nutzt, stimmst du unserer Verwendung von Cookies wie beschrieben zu. Du kannst deine Cookie-Einstellungen jederzeit über die Einstellungen deines Browsers verwalten.",
		'p-6' => "Weitere Details findest du in unserer",
		'privacypolicy' => "Datenschutzerklärung",
		'consent' => "Zustimmen",
		'noconsent' => "Nicht zustimmen",
	],
	'it' => [
		'h2-1' => "Benvenuto su Footble",
		'h3-1' => "Il gioco Wordle del calcio",
		'p-1' => "Utilizziamo cookie e tecnologie simili per migliorare la tua esperienza, analizzare le prestazioni del sito e fornire annunci personalizzati. Ecco cosa devi sapere",
		'localstorage' => "Archiviazione locale",
		'p-2' => "Footble memorizza i progressi del gioco (ad esempio, punteggi o impostazioni) direttamente nel tuo browser per funzionalità. Nessun dato personale viene raccolto o inviato a noi.",
		'analytics' => "Analytics",
		'p-3' => "Utilizziamo Google Analytics per capire come viene usato il nostro sito. Ciò può comportare l'uso di cookie per tracciare modelli di utilizzo anonimizzati.",
		'advertising' => "Pubblicità",
		'p-4' => "Collaboriamo con fornitori di annunci che possono utilizzare cookie per mostrare annunci pertinenti in base ai tuoi interessi e al tuo comportamento di navigazione.",
		'p-5' => "Continuando a utilizzare Footble, acconsenti al nostro uso dei cookie come descritto. Puoi gestire le tue preferenze sui cookie tramite le impostazioni del browser in qualsiasi momento.",
		'p-6' => "Per maggiori dettagli, consulta la nostra",
		'privacypolicy' => "Informativa sulla privacy",
		'consent' => "Acconsentire",
		'noconsent' => "Non acconsentire",
	],
];